<?php

namespace Database\Factories;

use App\Enums\TicketPriority;
use App\Enums\TicketStatus;
use App\Models\Category;
use App\Models\Team;
use App\Models\Ticket;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * The reference (GN-000123) is generated by the model after insert.
 *
 * @extends Factory<Ticket>
 */
class TicketFactory extends Factory
{
    public function definition(): array
    {
        return [
            'subject' => fake()->sentence(6),
            'description' => fake()->paragraphs(2, true),
            'category_id' => Category::factory(),
            'priority' => TicketPriority::NORMAL,
            'status' => TicketStatus::OPEN,
            'requester_id' => User::factory()->customer(),
            'assignee_id' => null,
            'team_id' => Team::factory(),
            'due_at' => now()->addHours(24),
        ];
    }

    public function status(TicketStatus $status): static
    {
        return $this->state(fn () => [
            'status' => $status,
            'resolved_at' => $status === TicketStatus::RESOLVED ? now() : null,
            'closed_at' => $status === TicketStatus::CLOSED ? now() : null,
        ]);
    }

    public function overdue(): static
    {
        return $this->state(fn () => ['due_at' => now()->subHour()]);
    }
}
